### PR TITLE
Link Chrome Extension with basic backend api call

### PR DESCRIPTION
**Pull request by nicasion**

### CODE REVIEW

**Comment by nicasion** [comment]
linked up with https://rival-app.azurewebsites.net/api/item - able to display name, original price, special price

**Comment by cggonzal** [comment]
@nicasion @yufanz is this ready to be merged to main?

**Comment by nicasion** [comment]
we can merge this branch first (as this was intermediate progress) and keep issue #17 open
will make a new PR based on the other branch react-adam that will resolve #17

**Review by cggonzal — APPROVED** [review]

**Comment by cggonzal** [comment]
Okay @nicasion I approved it. You can merge now ass needed.

**Pull request merged**
